"""sync_schema_fk_to_index_and_nullable

Revision ID: 003_sync_schema
Revises: 002_generated_reports
Create Date: 2026-02-18 12:36:51.100262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003_sync_schema'
down_revision: Union[str, None] = '002_generated_reports'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ai_chat_history_tenant_id'), 'ai_chat_history', ['tenant_id'], unique=False)
    op.drop_constraint('ai_chat_history_tenant_id_fkey', 'ai_chat_history', type_='foreignkey')
    op.create_index(op.f('ix_ai_digests_tenant_id'), 'ai_digests', ['tenant_id'], unique=False)
    op.drop_constraint('ai_digests_tenant_id_fkey', 'ai_digests', type_='foreignkey')
    op.alter_column('ai_scores', 'score_breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_ai_scores_tenant_id'), 'ai_scores', ['tenant_id'], unique=False)
    op.drop_constraint('ai_scores_tenant_id_fkey', 'ai_scores', type_='foreignkey')
    op.alter_column('alerts', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.drop_constraint('alerts_tenant_id_fkey', 'alerts', type_='foreignkey')
    op.create_index(op.f('ix_app_usage_logs_tenant_id'), 'app_usage_logs', ['tenant_id'], unique=False)
    op.drop_constraint('app_usage_logs_tenant_id_fkey', 'app_usage_logs', type_='foreignkey')
    op.alter_column('attendance_records', 'late_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('attendance_records', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.create_index(op.f('ix_attendance_records_tenant_id'), 'attendance_records', ['tenant_id'], unique=False)
    op.drop_constraint('attendance_records_tenant_id_fkey', 'attendance_records', type_='foreignkey')
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.drop_constraint('audit_log_tenant_id_fkey', 'audit_log', type_='foreignkey')
    op.alter_column('captured_orders', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'captured'::character varying"))
    op.create_index(op.f('ix_captured_orders_tenant_id'), 'captured_orders', ['tenant_id'], unique=False)
    op.drop_constraint('captured_orders_tenant_id_fkey', 'captured_orders', type_='foreignkey')
    op.alter_column('cash_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('ix_cash_records_tenant_id'), 'cash_records', ['tenant_id'], unique=False)
    op.drop_constraint('cash_records_tenant_id_fkey', 'cash_records', type_='foreignkey')
    op.alter_column('device_commands', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('device_commands', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('ix_device_commands_tenant_id'), 'device_commands', ['tenant_id'], unique=False)
    op.drop_constraint('device_commands_tenant_id_fkey', 'device_commands', type_='foreignkey')
    op.alter_column('devices', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('devices', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.drop_constraint('devices_tenant_id_fkey', 'devices', type_='foreignkey')
    op.alter_column('drivers', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('drivers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_drivers_tenant_id'), 'drivers', ['tenant_id'], unique=False)
    op.drop_constraint('drivers_tenant_id_fkey', 'drivers', type_='foreignkey')
    op.alter_column('generated_reports', 'filters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_generated_reports_tenant_id'), 'generated_reports', ['tenant_id'], unique=False)
    op.drop_constraint('generated_reports_tenant_id_fkey', 'generated_reports', type_='foreignkey')
    op.create_index(op.f('ix_location_logs_tenant_id'), 'location_logs', ['tenant_id'], unique=False)
    op.drop_constraint('location_logs_tenant_id_fkey', 'location_logs', type_='foreignkey')
    op.alter_column('maintenance_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('maintenance_records', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.create_index(op.f('ix_maintenance_records_tenant_id'), 'maintenance_records', ['tenant_id'], unique=False)
    op.drop_constraint('maintenance_records_tenant_id_fkey', 'maintenance_records', type_='foreignkey')
    op.alter_column('shift_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_shift_templates_tenant_id'), 'shift_templates', ['tenant_id'], unique=False)
    op.drop_constraint('shift_templates_tenant_id_fkey', 'shift_templates', type_='foreignkey')
    op.alter_column('shifts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.create_index(op.f('ix_shifts_tenant_id'), 'shifts', ['tenant_id'], unique=False)
    op.drop_constraint('shifts_tenant_id_fkey', 'shifts', type_='foreignkey')
    op.alter_column('tenants', 'country',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'KWT'::character varying"))
    op.alter_column('tenants', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Asia/Kuwait'::character varying"))
    op.alter_column('tenants', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'KWD'::character varying"))
    op.alter_column('tenants', 'subscription_plan',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'starter'::character varying"))
    op.alter_column('tenants', 'max_drivers',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('tenants', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tenants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('ticket_comments', 'attachments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('ix_ticket_comments_tenant_id'), 'ticket_comments', ['tenant_id'], unique=False)
    op.drop_constraint('ticket_comments_tenant_id_fkey', 'ticket_comments', type_='foreignkey')
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('tickets', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_tickets_tenant_id'), 'tickets', ['tenant_id'], unique=False)
    op.drop_constraint('tickets_tenant_id_fkey', 'tickets', type_='foreignkey')
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_users_tenant', table_name='users')
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.alter_column('vehicle_inspections', 'checklist',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('vehicle_inspections', 'photos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('vehicle_inspections', 'overall_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pass'::character varying"))
    op.create_index(op.f('ix_vehicle_inspections_tenant_id'), 'vehicle_inspections', ['tenant_id'], unique=False)
    op.drop_constraint('vehicle_inspections_tenant_id_fkey', 'vehicle_inspections', type_='foreignkey')
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'motorcycle'::character varying"))
    op.alter_column('vehicles', 'ownership',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'company'::character varying"))
    op.alter_column('vehicles', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_vehicles_tenant_id'), 'vehicles', ['tenant_id'], unique=False)
    op.drop_constraint('vehicles_tenant_id_fkey', 'vehicles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('vehicles_tenant_id_fkey', 'vehicles', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_vehicles_tenant_id'), table_name='vehicles')
    op.alter_column('vehicles', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('vehicles', 'ownership',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'company'::character varying"))
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'motorcycle'::character varying"))
    op.create_foreign_key('vehicle_inspections_tenant_id_fkey', 'vehicle_inspections', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_vehicle_inspections_tenant_id'), table_name='vehicle_inspections')
    op.alter_column('vehicle_inspections', 'overall_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pass'::character varying"))
    op.alter_column('vehicle_inspections', 'photos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('vehicle_inspections', 'checklist',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.create_index('idx_users_tenant', 'users', ['tenant_id'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'en'::character varying"))
    op.create_foreign_key('tickets_tenant_id_fkey', 'tickets', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_tickets_tenant_id'), table_name='tickets')
    op.alter_column('tickets', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.create_foreign_key('ticket_comments_tenant_id_fkey', 'ticket_comments', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_ticket_comments_tenant_id'), table_name='ticket_comments')
    op.alter_column('ticket_comments', 'attachments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('tenants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('tenants', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('tenants', 'max_drivers',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('tenants', 'subscription_plan',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'starter'::character varying"))
    op.alter_column('tenants', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'KWD'::character varying"))
    op.alter_column('tenants', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Asia/Kuwait'::character varying"))
    op.alter_column('tenants', 'country',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'KWT'::character varying"))
    op.create_foreign_key('shifts_tenant_id_fkey', 'shifts', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_shifts_tenant_id'), table_name='shifts')
    op.alter_column('shifts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'scheduled'::character varying"))
    op.create_foreign_key('shift_templates_tenant_id_fkey', 'shift_templates', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_shift_templates_tenant_id'), table_name='shift_templates')
    op.alter_column('shift_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_foreign_key('maintenance_records_tenant_id_fkey', 'maintenance_records', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_maintenance_records_tenant_id'), table_name='maintenance_records')
    op.alter_column('maintenance_records', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('maintenance_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_foreign_key('location_logs_tenant_id_fkey', 'location_logs', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_location_logs_tenant_id'), table_name='location_logs')
    op.create_foreign_key('generated_reports_tenant_id_fkey', 'generated_reports', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_generated_reports_tenant_id'), table_name='generated_reports')
    op.alter_column('generated_reports', 'filters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_foreign_key('drivers_tenant_id_fkey', 'drivers', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_drivers_tenant_id'), table_name='drivers')
    op.alter_column('drivers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('drivers', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_foreign_key('devices_tenant_id_fkey', 'devices', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.alter_column('devices', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('devices', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_foreign_key('device_commands_tenant_id_fkey', 'device_commands', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_device_commands_tenant_id'), table_name='device_commands')
    op.alter_column('device_commands', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('device_commands', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_foreign_key('cash_records_tenant_id_fkey', 'cash_records', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_cash_records_tenant_id'), table_name='cash_records')
    op.alter_column('cash_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_foreign_key('captured_orders_tenant_id_fkey', 'captured_orders', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_captured_orders_tenant_id'), table_name='captured_orders')
    op.alter_column('captured_orders', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'captured'::character varying"))
    op.create_foreign_key('audit_log_tenant_id_fkey', 'audit_log', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.create_foreign_key('attendance_records_tenant_id_fkey', 'attendance_records', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_attendance_records_tenant_id'), table_name='attendance_records')
    op.alter_column('attendance_records', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('attendance_records', 'late_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_foreign_key('app_usage_logs_tenant_id_fkey', 'app_usage_logs', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_app_usage_logs_tenant_id'), table_name='app_usage_logs')
    op.create_foreign_key('alerts_tenant_id_fkey', 'alerts', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('alerts', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_foreign_key('ai_scores_tenant_id_fkey', 'ai_scores', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_ai_scores_tenant_id'), table_name='ai_scores')
    op.alter_column('ai_scores', 'score_breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_foreign_key('ai_digests_tenant_id_fkey', 'ai_digests', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_ai_digests_tenant_id'), table_name='ai_digests')
    op.create_foreign_key('ai_chat_history_tenant_id_fkey', 'ai_chat_history', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_ai_chat_history_tenant_id'), table_name='ai_chat_history')
    # ### end Alembic commands ###
